### ISSUE TITLE
Using a grafana variable in the Parameter field

### ISSUE THREAD

**Issue by shaunlowis** [yamcs/grafana-yamcs#14]
Hi, when I set a value for a grafana variable, say, `my_var` is equal to `1` and try to use it in the parameter field of the yamcs plugin, I can't seem to use the normal syntax:
`some/yamcs/instance/param_${my_var}`

Which should evaluate to:
`some/yamcs/instance/param_1`

The error output just shows the raw value itself, not the formatted value:

```json
{
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/uid/ce94fwy6njugwd/api/mdb/testing/parameters/%24%7Bmy_var%7D",
    "hideFromInspector": false
  },
  "response": {
    "code": 404,
    "type": "NotFoundException",
    "msg": "No such parameter (missing namespace?)"
  }
}
```

I am probably doing something dumb. I tried wrapping the field in single and double quotes, inside and outside the brackets, but got the same error. I've also tried different variable types, but no luck! Any help would be appreciated, thank you for the great plugin!

**Comment by fqqb** [comment]
This appears to be unimplemented.
I see some seemingly straightforward instructions in the Grafana docs [1], so I can try that out, though will be later in the week.

[1] https://grafana.com/developers/plugin-tools/how-to-guides/data-source-plugins/add-support-for-variables

**Comment by shaunlowis** [comment]
Hi @fqqb , thank you for checking it out! I had a quick look today at this. I modified `ParameterQueryEditor.tsx`:

```typescript
import { getTemplateSrv } from '@grafana/runtime';

onParameterChange = (parameter?: string) => {
  const { onChange, query, onRunQuery } = this.props;
  // Resolve variables using Grafana's template service
  const resolvedParameter = parameter ? getTemplateSrv().replace(parameter) : undefined;
  onChange({ ...query, parameter: resolvedParameter });
  onRunQuery();
};
```

and got this working with a local dev build, to format a number into the `/TSE/simulator/battery_voltage$query0` field:

![image](https://github.com/user-attachments/assets/c7a4db26-5b95-45e7-8bc1-cf97dac47f8d)

However, when you "apply" this to the panel, the $query0 is overwritten with the current variable value, in this case "2", and is removed from the parameter field.

I think the suggestParameters or onTypeahead methods overwrite the input here and may need some modification. I hope this addition saves you some time when you get a chance to look at this.

**Comment by fqqb** [comment]
Thanks, I think your issue is because the substitution needs to occur at the moment of the query only, not during editing.

I've pushed a commit to master to seems to work fine in my tests, maybe you can also give it a try. If it works fine, I'll make a release.

Note that I have also updated the Grafana plugin framework to follow the latest conventions (tried against latest Grafana 11)

**Comment by shaunlowis** [comment]
Great, thanks for working on that! I just checked it out and I still see the format variable being overwritten in the parameter field. I don't think this is intended, as it means the variable won't work after editing the visualisation once. I've added a screen capture to show what I mean:

[Screencast from 2025-01-09 10-25-08.webm](https://github.com/user-attachments/assets/8d1181ec-ba9a-4afe-95e2-bf4603f747ae)

Perhaps I am doing something wrong at my end?

**Comment by fqqb** [comment]
Hmm strange because what's in your video is the scenario I was testing with (using a textbox variable). And in my case when i click outside the textbox, the plot immediately updates to reflect the change.

Is there a possibility this video is still using the previous code that you built? I had a similar issue like that by using `yarn build`, whereas `yarn dev` worked fine (didn't investigate deeper -- suspecting browser cache).

**Comment by shaunlowis** [comment]
@fqqb thank you! I ran:

```bash
git fetch && git pull

yarn upgrade typescript ts-node webpack webpack-cli
yarn build
yarn dev

docker compose up
```

Then my local build shows a variable working perfectly, thank you! Also works with custom variable.
Looks good to release to me!
